[build]
  publish = "public/"
  command = ""

[[redirects]]
  from = "/"
  to = "/fr/"
  status = 302
  conditions = { Language = ["fr"] }

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  conditions = { Language = ["en"]}
