[Settings]
  ID = "5b6c8bb2-14c3-4ad7-acdc-9f0338062df0"

[Build]
  Publish = ""
  Functions = ""

[[Redirects]]
  From = "/"
  To = "/fr/"
  Status = 302
  Force = false
  conditions = { Language = ["fr"] }

[[Redirects]]
  From = "/"
  To = "/en/"
  Status = 302
  Force = false
