[Settings]
  ID = "5b6c8bb2-14c3-4ad7-acdc-9f0338062df0"

[Build]
  Publish = "."
  Functions = ""

[[redirects]]
  from = "/"
  to = "/fr/"
  status = 302
  force = false

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = false
